language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - ./vendor/bin/parallel-lint src test
  - ./vendor/bin/phpunit --coverage-text test
  - ./vendor/bin/phpcs src --standard=psr2 -sp
